### ISSUE TITLE
Stale Godeps/_workspace/pkg breaking build

### ISSUE THREAD

**Issue by dpiddy** [tools/godep#45] opened 2013-12-20 01:24 UTC
I've been tracking heroku/hk lately and have had trouble with my `git pull && godep go build` flow. Worked with @bgentry to track it down today.

The problem seems to be that objects in `Godeps/_workspace/pkg` are stale but not rebuilt. Nuking that directory then running `godep go build` works.

Haven't dug into why yet but wanted to get an issue opened.

**Comment by dpiddy** [comment] 2015-01-16 15:15
Not sure if it's related to this or not but yesterday I had to nuke `$GOPATH/pkg` to get a `godep go install` to work.

**Comment by sqs** [comment] 2015-02-02 11:01
Following up on this, we experience this 100% of the time when checking out git branches with different files in `Godeps/_workspace/src` (because the old pkg files are there), git pulling commits that change files in `Godeps/_workspace/src`, editing `.go` files in `Godeps/_workspace/src`, etc. It's also something that confuses people we're onboarding. The workaround is to nuke the `Godeps/_workspace/pkg` dir, of course.

The thing that's kept me from digging into this more (beyond the repro at https://github.com/sqs/godeps-stale-pkg-repro) is that nobody else seems to experience this issue with such regularity. And that makes me suspect that something is different about our setup. For the other folks who have reported this, does this issue occur all of the time, or just occasionally?

**Comment by collinvandyck** [comment] 2015-02-06 18:48
@sqs hi I actually just ran into this today. I changed a dependency and ran a `godep go update [dep]`.  The JSON file seemed to be correctly updated, but the `.a` files in pkg were stale from a previous build. Nuking the pkg directory fixed it.

This is the first time I've run into this that I have noticed. I suspect/fear that it has been happening all along, periodically, but I just haven't noticed it for whatever reason.

**Comment by sqs** [comment] 2015-02-08 13:50
I think I found the root cause:

https://github.com/golang/go/blob/906aefb038b6baddc38f165bdfb6ecf624db398d/src/cmd/go/pkg.go#L784-L796

```
	// Have installed copy, probably built using current compilers,
	// and built after its imported packages.  The only reason now
	// that we'd have to rebuild it is if the sources were newer than
	// the package.   If a package p is not in the same tree as any
	// package named on the command-line, assume it is up-to-date
	// no matter what the modification times on the source files indicate.
	// This avoids rebuilding $GOROOT packages when people are
	// working outside the Go root, and it effectively makes each tree
	// listed in $GOPATH a separate compilation world.
	// See issue 3149.
	if p.Root != "" && !topRoot[p.Root] {
		return false
	}
```

It refers to https://github.com/golang/go/issues/3149.

I can see why you wouldn't want to recompile $GOROOT packages, but I wonder if the side effect of "mak[ing] each tree listed in $GOPATH a separate compilation world" is desirable. In this case, it is not.

**Comment by dpiddy** [comment] 2015-03-03 14:04
[On twitter](https://twitter.com/krarick/status/571818226016886784) @kr suggested `godep save -r` as a workaround. I have not been able to test yet.

**Comment by fkautz** [comment] 2015-04-02 21:18
As a workaround, we should be able to use:
```sh
godep go build -a
```

```-a``` tells go build to ignore mtime and assume everything is stale.

**Comment by fkautz** [comment] 2015-04-02 21:19
Can anyone see any reason why godep should not append -a on every build and install automatically?

**Comment by sqs** [comment] 2015-04-02 21:58
Always appending `-a` would slow down partial rebuilds, which would be undesirable for us (from a dev speed and iteration POV).

**Comment by fkautz** [comment] 2015-04-02 23:44
It would slow down builds, but by how much? On one of my projects, I saw build times increase by around 200ms. The increase in build times is likely acceptable for the added benefit of having correct builds. :)

**Comment by fkautz** [comment] 2015-04-03 01:05
Had a talk with @sqs offline, main problem is incremental builds, which typically run in 500ms vs full builds which run in around 7s.

We should probably push this upstream to the go team and get them to fix ```go build``` instead.

**Comment by shurcooL** [comment] 2015-04-14 18:35
There's a related issue (from Jan 2014) with discussion here:

https://github.com/jimmyfrasche/goutil/issues/2

We made a post on golang-nuts to try to motivate improving the situation upstream in Go, but it did not catch much attention:

https://groups.google.com/d/msg/golang-nuts/Z5uJf6mEF6E/K7yb6Xc5zQUJ

It was suggested to me by minux to make the thread in golang-dev (since Russ was away at the time), which I did, but it didn't get any traction either:

https://groups.google.com/forum/#!topic/golang-dev/svxuGkGJTD8

(Just mentioning relevant links here. I am extremely familiar with this issue and would really like to see it fixed, because it forces me to avoid installing my packages and thus lose benefits of faster compilation, auto completion, etc.)

**Comment by fkautz** [comment] 2015-04-14 19:37
@shurcooL How difficult would it be to submit a patch? One option would be to send them one and see if they accept it.

**Comment by shurcooL** [comment] 2015-04-14 20:28
**Summary:** It's quite difficult to come up with a patch that addresses the problem but doesn't create additional problems in edge cases.

The difficulty comes from having to consider _all_ edge cases - the `go` command has to deal with a lot. Most of those edge cases are less common, but still valid conditions where the `go` command is expected to behave correctly. An example would be building Go from source. In some cases, the `go` command needs to write to GOROOT workspace, in most other cases it should not.

It would require very careful consideration of all edge cases and planning, and seeing if it's possible to change the behavior such that this problem is resolved without compromising anything. If that can be done, I would imagine they would accept such a patch (after very thorough review).

At some point I had plans to try to do that, by making a fork of the `go` tool, making the changes I would want, and seeing if everything works out. I haven't gotten around to doing that (and I don't have short term plans to do it atm).

In the end, it may end up being trivial - or impossible. You can only find out after starting the work. It's quite hard to predict.

**Comment by shurcooL** [comment] 2015-06-19 20:38
This issue has been resolved in Go 1.5. See https://github.com/golang/go/issues/10509.

**Comment by kr** [comment] 2015-06-19 20:56
That is a relief. I'll go ahead and close this issue now. If folks come asking about it in the future we can direct them to update to Go 1.5.

@freeformz

**Closed by kr** 2015-06-19 20:56 UTC
Labels: bug

**Comment by fkautz** [comment] 2015-06-19 22:26
@shurcooL @kr Fantastic news, thanks for following up on this.
