### ISSUE TITLE
Stale subpackage binary breaking build

### ISSUE THREAD

**Issue by bgentry** [tools/godep#55] opened 2014-02-10 21:37 UTC
In hk, I recently added an `IsANSI()` func in the `github.com/heroku/hk/term` package.

With a fresh clone of this project and a `godep go build`, I see the following:

```
➜  hkstaging-build git:(staging) ✗ godep go build
# _/private/tmp/hkstaging-build
./main.go:187: undefined: term.IsANSI
godep: go exit status 2
```

Note that this is on Darwin, and the local file in `./term/unix.go` definitely contains the `IsANSI()` function. I dug a bit and noticed that I had a stale local binary object from this subpackage:

```
➜  hkstaging-build git:(staging) ✗ ls -la ~/go/pkg/darwin_amd64/github.com/heroku/hk/
total 536
drwxr-xr-x  4 bgentry  staff     136 Jan 17 13:10 .
drwxr-xr-x@ 5 bgentry  staff     170 Jan 17 13:10 ..
-rw-r--r--  1 bgentry  staff  225050 Jan 17 13:10 postgresql.a
-rw-r--r--  1 bgentry  staff   48476 Jan 17 13:10 term.a
```

Once I changed into my subpackage's dir (`~/go/src/github.com/heroku/hk/term`) and ran `go install`, this binary object was updated:

```
➜  hkstaging-build git:(staging) ✗ ls -la ~/go/pkg/darwin_amd64/github.com/heroku/hk/
total 536
drwxr-xr-x  4 bgentry  staff     136 Feb 10 13:32 .
drwxr-xr-x@ 5 bgentry  staff     170 Jan 17 13:10 ..
-rw-r--r--  1 bgentry  staff  225050 Jan 17 13:10 postgresql.a
-rw-r--r--  1 bgentry  staff   49134 Feb 10 13:32 term.a
```

Which allows the build to proceed normally:

```
➜  hkstaging-build git:(staging) ✗ godep go build
➜  hkstaging-build git:(staging) ✗
```

Is there something wrong with a build flag in my app, or is this something that Godep isn't accounting for?

**Comment by harshavardhana** [comment] 2015-03-30 19:47
https://github.com/tools/godep/blob/master/get.go#L50 - i cannot help but wonder why is "go install" necessary for "godep get" ?

**Comment by freeformz** [comment] 2015-09-11 18:57
Every time I've tracked these things down in the past it was because of the go tool using the wrong cached package file from outside. rewrites and/or vendor directory solve this AFAIK, so those should be used instead. Closing for now. If I'm way off base and/or we can reproduce with go 1.5* and current godep please re-open. Thanks!

**Closed by freeformz** 2015-09-11 18:57 UTC
Labels: bug

**Comment by bgentry** [comment] 2015-09-11 21:59
I'm almost positive this used to happen to me even with rewrites. But I'm
not using godep regularly enough right now to say if it's still an issue.
