### ISSUE TITLE
godep > v32 problems with build tags

### ISSUE THREAD

**Issue by dcelasun** [tools/godep#367] opened 2015-12-16 19:52 UTC
I'm using [gomail](https://github.com/go-gomail/gomail) which has 2 versions of `mime.go`, [one for Go 1.5+](https://github.com/go-gomail/gomail/blob/master/mime.go) and [one for everything else](https://github.com/go-gomail/gomail/blob/master/mime_go14.go).

When you `go get -u github.com/go-gomail/gomail` using, say, Go 1.5, the `gopkg.in/alexcesaro/quotedprintable.v3` dependency in `mime_go14.go` will not be installed. This is normally not a problem (e.g with `go build`), but `godep save -r` still tries to look for that package and fails:

    godep: Unable to find dependent package gopkg.in/alexcesaro/quotedprintable.v3 in context of /home/dcelasun/go/src/gopkg.in/gomail.v2

I understand *why* this happens, but how should it be fixed? Maybe godep could fetch such "missing" packages and vendor them as well? Not vendoring `mime_go14.go` (which is what godep<=v32 does) works fine as long as you don't change platforms / go versions, but that just defeats the purpose.

This might be related to #361, but I'm not using `GO15VENDOREXPERIMENT` so I've opened this as a separate issue.

**Comment by freeformz** [comment] 2015-12-17 18:52
This seems to work okay for me with current godep:

```console
$ mkdir ~/go2
$ export GOPATH=~/go2
$ go get -u github.com/go-gomail/gomail
$ cd ~/go2/src/github.com/go-gomail/gomail
$ godep save -r -v
godep: Unable to find dependent package gopkg.in/alexcesaro/quotedprintable.v3 in context of /Users/emuller/go2/src/github.com/go-gomail/gomail
$ # This is fine since it's an empty GOPATH
$ go get gopkg.in/alexcesaro/quotedprintable.v3 # This is the package that mime_go14.go uses
$ godep save -r -v
godep: cannot find package "gopkg.in/gomail.v2" in any of:
	/usr/local/go/src/gopkg.in/gomail.v2 (from $GOROOT)
	/Users/emuller/go2/src/gopkg.in/gomail.v2 (from $GOPATH)
$ go get gopkg.in/gomail.v2
$ godep save -r -v
godep: save: skipping test file: /Users/emuller/go2/src/gopkg.in/alexcesaro/quotedprintable.v3/encodedword_test.go
godep: save: skipping test file: /Users/emuller/go2/src/gopkg.in/alexcesaro/quotedprintable.v3/reader_test.go
godep: save: skipping test file: /Users/emuller/go2/src/gopkg.in/alexcesaro/quotedprintable.v3/writer_test.go
godep: save: skipping test file: /Users/emuller/go2/src/gopkg.in/gomail.v2/auth_test.go
godep: save: skipping test file: /Users/emuller/go2/src/gopkg.in/gomail.v2/example_test.go
godep: save: skipping test file: /Users/emuller/go2/src/gopkg.in/gomail.v2/message_test.go
godep: save: skipping test file: /Users/emuller/go2/src/gopkg.in/gomail.v2/send_test.go
godep: save: skipping test file: /Users/emuller/go2/src/gopkg.in/gomail.v2/smtp_test.go
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   example_test.go
	modified:   mime_go14.go

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Godeps/

no changes added to commit (use "git add" and/or "git commit -a")
$ # Files modified because of rewrites
$ find Godeps
Godeps
Godeps/_workspace
Godeps/_workspace/.gitignore
Godeps/_workspace/src
Godeps/_workspace/src/gopkg.in
Godeps/_workspace/src/gopkg.in/alexcesaro
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/encodedword.go
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/LICENSE
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/pool.go
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/pool_go12.go
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/reader.go
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/README.md
Godeps/_workspace/src/gopkg.in/alexcesaro/quotedprintable.v3/writer.go
Godeps/_workspace/src/gopkg.in/gomail.v2
Godeps/_workspace/src/gopkg.in/gomail.v2/.travis.yml
Godeps/_workspace/src/gopkg.in/gomail.v2/auth.go
Godeps/_workspace/src/gopkg.in/gomail.v2/CHANGELOG.md
Godeps/_workspace/src/gopkg.in/gomail.v2/CONTRIBUTING.md
Godeps/_workspace/src/gopkg.in/gomail.v2/doc.go
Godeps/_workspace/src/gopkg.in/gomail.v2/LICENSE
Godeps/_workspace/src/gopkg.in/gomail.v2/message.go
Godeps/_workspace/src/gopkg.in/gomail.v2/mime.go
Godeps/_workspace/src/gopkg.in/gomail.v2/mime_go14.go
Godeps/_workspace/src/gopkg.in/gomail.v2/README.md
Godeps/_workspace/src/gopkg.in/gomail.v2/send.go
Godeps/_workspace/src/gopkg.in/gomail.v2/smtp.go
Godeps/_workspace/src/gopkg.in/gomail.v2/writeto.go
Godeps/Godeps.json
Godeps/Readme
$ cat Godeps/Godeps.json
{
	"ImportPath": "github.com/go-gomail/gomail",
	"GoVersion": "go1.5",
	"Deps": [
		{
			"ImportPath": "gopkg.in/alexcesaro/quotedprintable.v3",
			"Rev": "2caba252f4dc53eaf6b553000885530023f54623"
		},
		{
			"ImportPath": "gopkg.in/gomail.v2",
			"Comment": "2.0.0-8-gfbb71dd",
			"Rev": "fbb71ddc63acd07dd0ed49ababdf02c551e2539a"
		}
	]
}
```

**Comment by dcelasun** [comment] 2015-12-17 19:10
> This is fine since it's an empty GOPATH

That's exactly my problem. If you are running Go>1.5, gomail doesn't need that dependency but godep, correctly, still wants to save it anyway. So maybe godep could fetch all such dependencies "hidden" behind build tags automatically?

**Comment by bobbyrullo** [comment] 2015-12-21 18:58
FYI running into this EXACT same problem on go 1.4.2

**Comment by freeformz** [comment] 2015-12-21 19:04
I plan on changing up the error message a bit to recommend a `godep get <pkg>` and then have the get command properly fetch all transitive deps (right now it can still miss some). As a possible additional step I was thinking of adding a `get` option to save (or just make it the default). For now you can fetch the other deps manually with `go get`.

**Comment by ericchiang** [comment] 2015-12-21 19:24
The issue is that godep running go 1.4.X is looking into a file with a `// +build go1.5` tag and finding an import that doesn't exist in go 1.4.X.

Here's the files that are causing trouble.

```
$ head mime.go 
// +build go1.5

package gomail

import (
	"mime"
	"mime/quotedprintable"
)

var newQPWriter = quotedprintable.NewWriter
$ head mime_go14.go 
// +build !go1.5

package gomail

import "gopkg.in/alexcesaro/quotedprintable.v3"

var newQPWriter = quotedprintable.NewWriter

type mimeEncoder struct {
	quotedprintable.WordEncoder
```

The go tool itself correctly states that `mime/quotedprintable` isn't part of the imports for this package when using go 1.4.X

```
$ go version gopkg.in/gomail.v2
go version go1.4.3 linux/amd64
$ go list -f '{{.Imports}}'
[bytes crypto/tls encoding/base64 errors fmt gopkg.in/alexcesaro/quotedprintable.v3 io mime mime/multipart net net/mail net/smtp os path/filepath time]
```

However godep thinks that `mime/quotedprintable` is a dependency when running go 1.4.X

**Comment by freeformz** [comment] 2015-12-21 19:36
Maybe godep should also handle build tags based on the version specified in Godep.json? That does open up a different set of problems (like additional work on `godep update -goversion`). ATM godep will vendor every dep it finds, regardless of tags (except for `ignore` and `appengine`), this is by design.

**Comment by ericchiang** [comment] 2015-12-21 19:46
Okay that makes sense. Then the issue here is that `mime/quotedprintable` isn't a go getable package since it's part of the standard library.

```
$ godep restore
godep: Dep (gopkg.in/gomail.v2) restored, but was unable to load it with error:
	Unable to find dependent package mime/quotedprintable in context of /home/eric/src/gopkg.in/gomail.v2
godep: 	This may be because the dependencies were saved with an older version of godep (< v33).
godep: 	Try `go get mime/quotedprintable`. Then `godep save` to update deps.
godep: Error checking some deps.
```

Can godep keep a white list of standard library packages for all go versions, then skip these when attempting to restore a package?

**Comment by dcelasun** [comment] 2016-01-20 07:02
@freeformz Any updates on this?

**Comment by freeformz** [comment] 2016-01-20 17:33
Not yet, I am thinking that godep should probably use the recorded go version in conjunction with build tags to DTRT and not analyze deps for go versions that differ from what's recorded. The idea being that what's recorded as the go version is the version in use and the one being tested against. But I'm sure some people would disagree with that. There is an argument to be made for either case. For instance see #386

**Comment by freeformz** [comment] 2016-05-20 18:34
Recent versions of go record the version of go in use and also support go version build tags, so I'm closing this.

**Closed by freeformz** 2016-05-20 18:34 UTC

**Comment by PolyviosT** [comment] 2016-09-06 10:54
Hello,
 Any update on this?  Godep is including all deps it finds regardless of tags (except for ignore and app engine). So the issue here is that  for the mux module of gorilla they have this tag under context_gorilla: // +build !go1.7. So if you try to do a godep it will ignore the context module and will be missing from the vendor folder. Any workaround on that?
