### ISSUE TITLE
Godep gives a godep: "Package not found" error when trying to add a new library to an project already using godep

### ISSUE THREAD

**Issue by nithin-bose** [tools/godep#447] opened 2016-04-03 07:01 UTC
I have a project where I am using godep. I started the project from scratch, i did a ``go get`` for all my dependencies, i did a ``godep save`` and godep moved all the dependencies to the vendor folder and every thing works as expected.

But when I add a new dependency and tried to run ``godep save`` again, it gives me a  "Package not found" error for packages already moved to the vendor folder by godep previously. 

Am i doing something wrong here??

**Comment by galeone** [comment] 2016-04-06 13:30
@nithin-bose are you getting the message `godep: Package (context) not found`?
I'm asking this because I've this problem and I guess it's the same as yours.

All I'm trying to do is to run a godep save on a clean new project, and I got this error.

**Comment by freeformz** [comment] 2016-04-06 21:06
@galeone See #451, which was merged as v61.

**Comment by ddollar** [comment] 2016-04-21 13:40
I'm getting a similar error to @galeone . I'm on v61 and go 1.6.1

Trying to re-run `godep save` gives me `godep: Package (fmt) not found`

**Comment by freeformz** [comment] 2016-04-21 14:26
Hmm. 'fmt' is a stdlib package and should be easily found. Is your go install special in any way? How was it installed? Are symlinks involved?

**Comment by ddollar** [comment] 2016-04-21 15:04
No symlinks. Both godep and go installed from Homebrew.

**Comment by freeformz** [comment] 2016-04-22 01:33
@ddollar I can't seem to replicate this with the same install. Can your provide a link to a copy of the output from `godep save -d -v <pkg spec> >log 2>&1` ? The output may be huge, so it may not attach here.

**Comment by ddollar** [comment] 2016-04-22 13:01
Now I can't replicate it either. If it shows back up again I'll grab a log.

**Comment by kr** [comment] 2016-04-22 19:27
> Both godep and go installed from Homebrew.

(Offtopic) pro tip: don't install Go from homebrew (or any package manager). Download a tarball from https://golang.org/dl/ and unzip it into /usr/local/go.

**Comment by stroborobo** [comment] 2016-05-06 07:27
Had this problem with stdlib packages in v61 as well. In v63 it only complained about third party packages. Funny thing is: I ran `godep update $mypackage` and it complained about another package that was in fact missing in my GOPATH.

@kr Why?

**Comment by freeformz** [comment] 2016-05-06 17:21
@stroborobo `go get` obeys local arch. Since code can be deployed to different architectures godep looks at all dependencies. So when you `godep save` cross arch deps may be missing. I'm not sure what the best solution to that is.

**Comment by stroborobo** [comment] 2016-05-06 19:54
Hey @freeformz :)

Sorry, but how is this relevant for any of the two? In the first case I tried to update a specific package and godep complained that another package is missing. Why would it even check for it's existence? In @kr's suggestion it's about precompiled binaries, but both the homebrew and the golang.org version of Go are precompiled, so where's the difference? And shouldn't godep installed via homebrew rely on GOPATH no matter on which machine is's been compiled on or where it's located on disk?

**Comment by freeformz** [comment] 2016-05-06 20:11
@stroborobo my comment was wrt third party packages, not the stdlib. godep relies on the $GOPATH reguardless of installation method. As I mentioned above I wasn't able to replicate this with the "same install", meaning I removed my own godep / go and installed them via homebrew. Furthermore I was trying to clarify how godep analyzes packages. It always relies on $GOPATH, but can pull in extra transitive deps across architectures vs. `go get`. This is important if you develop on OSX, but deploy to Linux, which is a very common case.

**Comment by stroborobo** [comment] 2016-05-06 20:35
How to reproduce with third party packages, note how I the updated package and the missing one are different:

```
bo-mpb:bo [~/src/go/src/github.com/stroborobo/godep-not-found]I> < Godeps/Godeps.json
{
        "ImportPath": "github.com/stroborobo/godep-not-found",
        "GoVersion": "go1.6",
        "GodepVersion": "v63",
        "Deps": [
                {
                        "ImportPath": "github.com/stroborobo/ansirgb",
                        "Rev": "c938d9fb2e25c965c50f2440483f7c6107b6c71b"
                },
                {
                        "ImportPath": "github.com/stroborobo/myfmt",
                        "Rev": "2320937f75d54eff996d1d4b1bff673a2e76bfec"
                }
        ]
}
bo-mpb:bo [~/src/go/src/github.com/stroborobo/godep-not-found]I> ..
bo-mpb:bo [~/src/go/src/github.com/stroborobo]I> mv myfmt/ myfmt.bak
bo-mpb:bo [~/src/go/src/github.com/stroborobo]I> popd
bo-mpb:bo [~/src/go/src/github.com/stroborobo/godep-not-found]I> godep update github.com/stroborobo/ansirgb
godep: Package (github.com/stroborobo/myfmt) not found
bo-mpb:bo [~/src/go/src/github.com/stroborobo/godep-not-found]I>
```

Doesn't `go get` download the complete source code regardless of architecture? How does that differ from godep exactly? I thought godep copied the needed packages into vendor/, stripping subdirectories and stuff.

**Comment by freeformz** [comment] 2016-05-06 21:08
If $GOPATH/github.com/stroborobo/myfmt isn't there then you will get not found because the package isn't in $GOPATH. The way godep currently works is that to update / save deps the packages need to be in the $GOPATH, even if they are already saved. This is for various reasons.

Re: `go get`. Yes and No. Yes, in that `go get` fetches all the source code for your current os/architecture. No, in that the same code can require additional transitive dependencies on different os/architectures. I'm not sure if that's what happened here, but it's likely.

**Comment by nithin-bose** [comment] 2016-05-07 13:20
So does godep check the vendor folder for dependencies?? Especially in go 1.6 and above??

**Comment by stroborobo** [comment] 2016-05-09 07:18
@freeformz 

> The way godep currently works is that to update / save deps the packages need to be in the $GOPATH, even if they are already saved.

I see, assumed it's a bug.

> No, in that the same code can require additional transitive dependencies on different os/architectures.

Of course, thanks! ;)

@nithin-bose It does, you'll still have a `Godep/` dir though, but it only contains the JSON file (and a Readme).

**Comment by freeformz** [comment] 2016-05-09 17:21
@stroborobo Maybe I should treat it as a bug.

**Comment by nithin-bose** [comment] 2016-05-09 18:16
@stroborobo the only difference I can see while init-ing a project and adding a new dependencies to an existing project using godep is that in the first case, the dependencies are in the ``src`` folder, whereas in the second case, godep has already moved existing dependencies to the ``vendor`` folder...

**Comment by hadv** [comment] 2016-07-06 03:55
I have the same problem here :(

**Comment by freeformz** [comment] 2016-07-06 22:42
@hadv context is part of go1.7 and therefore requires tip or a go1.7 build.

**Closed by freeformz** 2016-07-06 22:42 UTC

**Comment by hadv** [comment] 2016-07-08 07:17
@freeformz so, how can we use godep for go1.6? Thank you!

**Comment by freeformz** [comment] 2016-07-08 19:21
@hadv what version of godep are you using? I added support for handling go version build tags a few months ago, so this should work if the lib you are importing is conditionally importing context behind a build flag (unless your godep version is old). 

Otherwise the package you are using is just blankly importing context no matter of go version and the package needs to be fixed.

**Comment by hadv** [comment] 2016-07-09 08:46
@freeformz thank you, I updated the latest version of godep then it's ok now!

**Comment by Gnouc** [comment] 2016-07-13 06:48
I upgraded my go version to `go1.7rc1`, and `godep` stop working:

```
godep save ./...
zsh: correct './...' to './..' [nyae]? n
godep: Package (github.com/google/gofuzz) not found
```

**Comment by jingweno** [comment] 2016-07-19 17:01
Same problem here with `go1.7rc2`:

```
$ godep save ./...
godep: Package (bytes) not found
```

**Comment by tejasmanohar** [comment] 2016-07-20 20:44
Same issue 
```
$ go version
go1.6.3 darwin/amd64
```

**Comment by freeformz** [comment] 2016-07-22 00:34
@Gnouc does anything use it transitively ? 
@jingweno I can't replicate, can you provide a step by step reproducer using go1.7rc3 and a clean gopath?
@tejasmanohar This issue talks about several different problems AFAICT, can you be more specific?

**Comment by tejasmanohar** [comment] 2016-07-22 00:44
```
$ godep save ./...
godep: Package (encoding/json) not found
```

**Comment by freeformz** [comment] 2016-07-25 20:30
Sounds like a problem with the version of go you are using or your install
of go.

**Comment by jianzhangbjz** [comment] 2016-08-02 03:49
I encounter a similar error to @nithin-bose, i git clone the K8s project(used godep manager packages), and when I add a new package(locally) and exec `godep save -d -v nvidia-docker/nvidia > jian.log 2>&1` command, errors as the following:
```
 versionString() godep v74 (linux/amd64/go1.6.2)
majorGoVersion go1.6
VendorExperiment true
sep /vendor/
dotPackageImportPath: k8s.io/kubernetes
dotPackageDir: /root/code/kubernetes/src/k8s.io/kubernetes
godep: Go Version: go1.6
godep: Finding dependencies for [nvidia-docker/nvidia]
LoadPackages [nvidia-docker/nvidia]
listPackage nvidia-docker/nvidia
findDirForPath nvidia-docker/nvidia <nil>
searching /usr/local/go/src/nvidia-docker/nvidia
searching /root/code/kubernetes/src/nvidia-docker/nvidia
godep: Package (nvidia-docker/nvidia) not found
```
Am I doing something wrong here? How to solve it?

**Comment by jayunit100** [comment] 2016-08-17 17:11
something weird for me to , i think this might be the same error
```
➜  kubernetes git:(config-e2e-file) ✗ go version 
go version go1.7 darwin/amd64
➜  kubernetes git:(config-e2e-file) ✗ godep version
godep v74 (darwin/amd64/go1.7)
```

**Comment by freeformz** [comment] 2016-08-17 17:23
`godep save -d -v nvidia-docker/nvidia` is telling godep to analyze and
save the deps for the `nvidia-docker/nvidia` package. Is that what you want?

**Comment by ajayamohan** [comment] 2016-09-23 01:46
Similar issue:
`
$godep save ./...
godep: Package (github.com/kr/logfmt) not found
`

Versions:
$go version
go version go1.7 darwin/amd64
$godep version
godep v74 (darwin/amd64/go1.7)

**Comment by ufukomer** [comment] 2016-10-05 23:59
Why is that?

`godep: Package (github.com/hashicorp/go-cleanhttp) not found`

**Comment by freeformz** [comment] 2016-10-06 03:54
The package is transitively required, possibly in a way where `go get` may
not fetch it. `go get github.com/hashicorp/go-cleanhttp` it directly. and
re-save. I the error happens again with the same package there is a
problem. If it happens again with a different package, `go get` that
package. Rinse and repeat until save. You should only need to do this until
all of the transitive deps are local.

**Comment by alyssaq** [comment] 2016-11-03 07:18
Running into this issue:
```
$ godep save ./...
godep: Package (github.com/stretchr/testify/assert) not found
```
```
$ go version
go version go1.7.1 darwin/amd64
$ godep version
godep v75 (darwin/amd64/go1.7.1)
```

**Comment by freeformz** [comment] 2016-11-04 18:08
go get github.com/stretchr/testify/assert; godep save ./...

**Comment by yhung124** [comment] 2016-11-10 03:09
Same here
```
$ go version
go version go1.7.1 linux/amd64
$ godep version
godep v75 (linux/amd64/go1.7.1)
```
I use a workaround method to get all missing packages, but I don't think it's a good idea.
```
#!/bin/bash
rc="$(godep save 2>&1)"
while echo $rc | grep "not found";
do
  package=$(echo $rc | sed -n "s/godep: Package (\(.*\)) not found/\1/p")
  go get $package
  rc="$(/home/build/go/bin/godep save 2>&1)"
done
```

**Comment by freeformz** [comment] 2016-11-11 18:48
godep works off the packages in your $GOPATH. if it can't find a package in
your $GOPATH, then it can't save it, so you need to manually `go get` it
before saving.

**Comment by ychen-symphony** [comment] 2016-11-15 00:16
Same here. I am adding a new package to the same code, and getting two different errors from two different Mac OSX machines.

On one machine, I simply cannot run `godep save ./...`, it will report error `godep: dirty working tree` error. Tried it on another machine and now I am getting `godep: Package (context) not found`.

**Comment by freeformz** [comment] 2016-11-16 01:46
What version of godep are you on?

If the working tree of a dep is dirty is should say what the dep is. That
needs to be resolved as godep won't know what to vendor if the dep's
working tree is dirty.

I'm pretty sure the restriction on the local project being dirty was
removed many versions ago.

On the other machine I am assuming you have an older version of go/godep as
well.

**Comment by ychen-symphony** [comment] 2016-11-16 03:50
Hi,

I am using recent go and godep versions on both Mac OSX machines.  I was
able to solve the problem on the machine that reports "Package (context)
not found" by running "go get -u ./...", but the issue for dirty working
tree still persist.

$ godep version
godep v75 (darwin/amd64/go1.7.3)
$ go version
go version go1.7.3 darwin/amd64
$ godep save
godep: dirty working tree (please commit changes): /Users/yichen/go/src/
google.golang.org/cloud
godep: dirty working tree (please commit changes): /Users/yichen/go/src/
google.golang.org/cloud/compute/metadata
godep: dirty working tree (please commit changes): /Users/yichen/go/src/
google.golang.org/cloud/datastore
godep: dirty working tree (please commit changes): /Users/yichen/go/src/
google.golang.org/cloud/datastore/internal/proto
godep: dirty working tree (please commit changes): /Users/yichen/go/src/
google.golang.org/cloud/datastore/internal/type_proto
godep: dirty working tree (please commit changes): /Users/yichen/go/src/
google.golang.org/cloud/internal
godep: dirty working tree (please commit changes): /Users/yichen/go/src/
google.golang.org/cloud/internal/transport
godep: error loading dependencies

**Comment by freeformz** [comment] 2016-11-16 04:32
So the packages in google.golang.org/cloud have local, uncommitted changes.
Or something else is going on. If you "cd /Users/yichen/go/src/
google.golang.org/cloud" and run "git status ", what does it say?

**Comment by ychen-symphony** [comment] 2016-11-16 04:37
Aha so "git status" says the "HEAD detached at abc5503". Did "git checkout
master" and now godep save works!

I didn't realize the message dirty working tree meant the dependencis, not
my working repo. Thanks for the help!

**Comment by Narven** [comment] 2016-12-16 22:53
Just leaving here a tip that was helpful for me when running `godep save` I was getting `godep: Package (fmt) not found`.

I ran `go get github.com/tools/godep` and then `godep save` and it worked.

Probably I was running some old version.

**Comment by folex** [comment] 2017-02-04 11:56
Had `Package (fmt) not found` error. both `go` and `godep` were installed via `brew`.
```
$ go version
go version go1.7.5 darwin/amd64
```
The problem was that I was using `godep v78`, after updating to `v79` via
```
$ brew unlink godep
$ brew install godep
```
error is gone. Hope it will help someone.

**Comment by skytask** [comment] 2017-06-25 21:26
Same issue
godep: package ( {various packages} ) not found

**Comment by m1093782566** [comment] 2017-07-22 02:46
godep will not find packages in vendor?

**Comment by freeformz** [comment] 2017-08-07 21:21
It does, but you should consider migrating to [dep](https://github.com/golang/dep) or [govendor](https://github.com/kardianos/govendor) instead.

**Comment by dmigwi** [comment] 2018-02-15 15:08
The solution to this issue is that, Some packages are missing your default GOPATH where `go get <package link>` command clones them to.
So run, **godep restore** to clone again all the missing  dependencies then continue with the process of adding the new dependency.

**Comment by cassioconti** [comment] 2018-06-12 03:38
Thanks @dmigwi. I run a `godep restore` first. For me, after that the `godep save` started working.
