### ISSUE TITLE
Import error for Google Appengine packages

### ISSUE THREAD

**Issue by matthewbelisle-wf** [tools/godep#103] opened 2014-07-16 20:01 UTC
Google Appengine is a common platform for Go apps, but godep can't save appengine packages because the appengine SDK shims its import paths instead of using normal VCS based import paths.  So instead of `import "github.com/something/appengine/datastore"` it does `import "appengine/datastore"` and then shims the imports somehow to point to the SDK paths for the package.

https://github.com/GoogleCloudPlatform/appengine-guestbook-go/blob/32112ced8de3e8e02bd64801f99f776527c62f23/hello.go#L8

This is a problem because godep throws an error when it tries to import these,

```
$ godep save .
godep: cannot find package "appengine/datastore" in any of:
        /usr/local/Cellar/go/1.3/libexec/src/pkg/appengine/datastore (from $GOROOT)
        /Users/mgbelisle/go/src/appengine/datastore (from $GOPATH)
godep: error loading dependencies
```

which makes sense but is unfortunate.  What is the proper way to fix that?  This change here works but seems a little kludgy.

https://github.com/matthewbelisle-wf/godep/commit/dba190f14fc83759b74df44e4ab4e7a492eedb1d

**Comment by fredr** [comment] 2015-01-19 15:43
+1

**Comment by fredr** [comment] 2015-01-20 00:00
@kr the -ignore flag, do you want it to be a comma separated list of import paths, or a regex?

**Comment by arschles** [comment] 2015-03-28 20:51
+1 on this. I'd be ok with CRLF delimited

**Comment by vvakame** [comment] 2015-06-22 05:58
:+1:

**Comment by sinmetal** [comment] 2015-06-22 06:30
:+1:

**Comment by freeformz** [comment] 2015-06-22 21:14
@neurogeek you may be interested in this one?

**Comment by neurogeek** [comment] 2015-06-22 21:57
Sure, I'll take a look later today.

**Comment by kalbasit** [comment] 2015-06-22 23:19
I don't believe that this is necessary any longer as the legacy appengine packages were replaced by the ones that run on both appengine and managed appengine. See [this](https://code.google.com/p/googleappengine/issues/detail?id=11670) and [this](https://github.com/golang/appengine#updating-a-go-app-engine-app) for more information.

I am currently using [`google.golang.org/appengine`](https://github.com/go-acd/oauth-server/blob/master/goapp/roothandler.go#L10) in my project hosted by Google Appengine (not within a Managed VM). I just omitted `vm:true` from [`app.yaml`](https://github.com/go-acd/oauth-server/blob/master/appengine/app.yaml).

**Comment by neurogeek** [comment] 2015-06-23 01:39
@kalbasit: Interesting. With new qualification over appengine packages, we definitely don't need this.
Having said that, I'm inclined to have the omit/ignore flag anyways, just not appengine-centric, since we could run into this in the future. What do you guys think?

**Comment by freeformz** [comment] 2015-06-23 03:10
@neurogeek What are the use cases for an `omit` flag? My intent is not challenging it, I'm asking to clarify your reasoning.

**Comment by neurogeek** [comment] 2015-07-15 02:10
@freeformz Sorry it took me a while to answer, rough past few weeks at work.
I don't have an answer for you :) I guess I was thinking on ad-hoc workflows that could benefit from having `omit`.

I'll close this and if needed, people can issue a feature request.

**Comment by ronoaldo** [comment] 2015-08-06 02:39
Sorry to "revive" this but the comment regarding appengine pacakges beign "replaced" is misleading, as the new packages are targeted to Managed VMs, and they provide a layter for compatibility that, once built with App Engine SDK (or with the build flag +appengine), will end up importing appengine/* imports as well. Given the fact that App Engine is now out of beta and the classic packages + SDK will follow the deprecation policies, I think this is a real issue.

If you are working with App Engine and run godep save it will not work. I think that a solution like -omit is nice, but should be also recorded in Godep.json, so it would be recorded in the revision control and help other users working on the same repo/codebase to take advantage of that.

**Comment by pshevtsov** [comment] 2015-08-13 21:27
:+1: for `-omit`. I agree with @ronoaldo, using `google.golang.org/appengine` packages is not a true replacement for `appengine` packages.

**Comment by neurogeek** [comment] 2015-08-14 18:50
Ok..
Let's reopen and I'll take a better look over the weekend.

**Comment by pshevtsov** [comment] 2015-08-14 23:18
Thank you @neurogeek! We really appreciate it! :+1:

**Comment by pshevtsov** [comment] 2015-08-17 11:36
Hey @neurogeek! Have you had the chance to look at this issue? Thanks

**Comment by kalbasit** [comment] 2015-08-17 16:19
@dsymonds I think the community is quite confused about the fate of the Appengine SDK versus the Appengine packages, can you please clarify?

**Comment by neurogeek** [comment] 2015-08-17 16:46
Ok, I took a look and also asked around and yes, Go on Appengine needs to be handled differently. The Appending SDK is the new-ish thing, but Appengine packages aren't going away anytime soon.
Lets implement the -omit flag. @kr @freeformz on board?

**Comment by dsymonds** [comment] 2015-08-19 08:07
`google.golang.org/appengine` and friends are intended to be a replacement for `appengine` and friends. If there's a reason why that's not the case, it's a bug (yes, there's a couple of known gaps that we're working on).

They aren't "replacements" completely, though; any existing app using `import "appengine"` is going to continue to work, though I think it's fine for various tools to only work properly with the new ones.

**Comment by freeformz** [comment] 2015-08-20 00:37
@neurogeek I'd rather not add -omit if we can help it.

@dsymonds Does this mean that users should `import "google.golang.org/appengine"` instead of `import "appengine"` and apply any updates necessary?

**Comment by ronoaldo** [comment] 2015-08-20 02:09
Currently, I'm using the `import "appengine"` statements on lots of places, including some tools. The way I'm handling vendor on these apps is by vendoring the vendor tool itself: we have a cmd/godep copy that is, basically, a copy from this fork `https://github.com/fredr/godep`, which works out of the box on both cases. The problem is that this causes confusion, as I have to instruct any team member or new collaborator to checkout a different copy o godep to make it work.

Also, I just noted that if you run `godep` with a `$GOROOT` pointing to the App Engine GOROOT (which I was expecting to work, as the appengine package exists there), it does not. The reason is that `go list -e -json` cannot find any packages at all, since the App Engine SDK `$GOROOT` does not have the `src/pkg` folder; all sources are at the `src/` folder directly (i.e., src/time instead of src/pkg/time).

So, to sum up my experiences so far:
- You can't use `github.com/tools/godep` with `import "appengine"`
- Even if you `export $(goapp env)`, you still can't use godep because $GOROOT/src/pkg does not exist.
- If you have an existing app and want to use godep for vendoring, you have to rewrite a reasonable amount of code to move `import "appengine"` to `import "google.golang.org/appengine"`
- You end up vendoring the vendor tool itself, which is where I am at now until I can move to the new packages.

I'm just wondering if there is a better/recommended way to work with both tools, and avoid the confusion that I am having. If the only supported way is the new imports, then let it be - I would suggest that maybe it worth adding this to the documentation.

The -omit flag may not solve the problem; maybe a special case for appengine/* would help everyone, even if transitivelly until the new packages are more widelly addopted.

**Comment by dsymonds** [comment] 2015-08-20 02:12
@freeformz: If the newer packages work for you, sure. They'll be the best supported ones in the long term.

Switching to `google.golang.org/appengine` should not entail rewriting a lot of code. 95% of the APIs are exactly the same, so it should only be a matter of rewriting the import statement; the `google.golang.org/appengine` README has a sed command to do that very quickly.

**Comment by freeformz** [comment] 2015-08-20 04:23
@dsymonds @ronoaldo For reference that README is here right? https://github.com/golang/appengine

**Comment by pshevtsov** [comment] 2015-08-20 09:58
@freeformz @ronoaldo https://github.com/golang/appengine#2-update-import-paths

> ```
sed -i '/"appengine/{s,"appengine,"google.golang.org/appengine,;s,appengine_,appengine/,}' \
  $(find . -name '*.go')
```

**Comment by ronoaldo** [comment] 2015-08-20 18:11
@dsymonds @freeformz @pshevtsov thanks. I am happy that the recommendation is then to move to the new packages, which hence are compatible with `godep`, and that the new App Engine packages are long-term support.

**Comment by freeformz** [comment] 2015-08-20 18:35
Awesome. I'm going to close this issue out again then as I think it documents what people should do.

**Closed by freeformz** 2015-08-20 18:35 UTC
Labels: feature

**Comment by vishalshah-org** [comment] 2015-12-08 10:11
Guys, but `google.golang.org/appengine` itself imports `appengine`. And hence godep consistently complains "appengine" package is missing. Anyone here who can offer help?

Thanks.

**Comment by vishalshah-org** [comment] 2015-12-08 19:01
@freeformz just found out the above error is pertaining to https://github.com/tools/godep/issues/348
