### ISSUE TITLE
checking go version breaks GO15VENDOREXPERIMENT compat on go-1.4

### ISSUE THREAD

**Issue by thockin** [tools/godep#386] opened 2015-12-28 08:09 UTC
As noted in #378, `godep save` now fails for me - specifically I have go-1.4 on this machine, but I am setting GO15VENDOREXPERIMENT=1 so that I can make a repo that works best in go-1.5, but still works with go-1.4.  godep v43 runs `godep save ./...` for a few minutes, then exits 0, but has not made any changes to the repo at all.  adding `-v` prints nothing at all.

**Comment by c-knowles** [comment] 2015-12-28 09:18
How about with running ```godep save -d ./...```? Does the debug mode reveal anything?

**Comment by thockin** [comment] 2015-12-28 19:13
Interestingly: if I `rm -rf Godeps/_workspace/src` before `godep save`
(even without the vendor experiment) godep does not restore any of the
source files.  I guess it trusts Godeps.json, so I have to remove the whole
Godeps directory, which is sort of obnoxious.

If I set `export GO15VENDOREXPERIMENT=1` godep still restores to
`Godeps/_workspace/src`, rather than `vendor` when my Go version is 1.4 - I
want godep to NOT pay attention to my local go version.

**Comment by freeformz** [comment] 2015-12-28 21:14
@thockin godep does not verify if what you have in the workspace is what's recorded in `Godeps.json`. That is kind of hard tbh w/o messing with your $GOPATH and/or downloading a bunch of stuff. So yes, it assumes that if it's in Godeps.json that it's in your workspace. 

GO15VENDOREXPERIMENT only means something to go versions >= 1.5, so I don't really understand the use case for 1.4 versions of go.

**Comment by thockin** [comment] 2015-12-28 21:17
My local version of Go is not the version that I use to build my project.
Having godep check go version is inappropriate - I asked for it to use the
new vendoring format.

**Comment by freeformz** [comment] 2015-12-28 21:23
I have to enable the vendor experiment if the target version of go is 1.6 and the environment variable != "0". It's what I would expect as a developer.

I think this would work better for you...
```go
	go15ve := os.Getenv("GO15VENDOREXPERIMENT")
	VendorExperiment = go15ve == "1" || (majorGoVersion == "go1.6" && go15ve != "0")
```

**Comment by freeformz** [comment] 2015-12-28 21:27
TBH though I wouldn't expect that env var to do anything when using any version of go < 1.5

**Comment by thockin** [comment] 2015-12-28 22:00
I wouldn't expect that env var to do anything for the `go` program, but
`godep` defines it as writing into the go-1.5 compatible location.  Except
when $unrelated_thing causes it to not.  I think your proposed condition
sounds better.

**Comment by freeformz** [comment] 2015-12-28 22:30
My intention when introducing `GO15VENDOREXPERIMENT` support was to mirror the go tool's behavior. With go 1.4 that flag doesn't mean anything. Since we no longer depend on `go list` I felt a stricter interpretation within godep was necessary to be more closely align with the go tool.

PS: Why aren't you using go 1.5.2 locally at this point?

**Comment by thockin** [comment] 2015-12-28 22:37
We support both go-1.4 and go-1.5 and because we still have some
1.5-related problems I keep 1.4 around on one machine.

**Comment by freeformz** [comment] 2015-12-28 23:28
@thockin godep defines it's GO15VENDOREXPERIMENT flag like the go tool. So when using go1.4 it shouldn't do anything wrt that flag. I probably should have specified harder checks initially, but I really didn't expect people to *want* to use it with go1.4 in that way, nor do I think most of our users. So I'm going to close this as "works as intended" in a few days unless others pipe up that my expectations are way off base.

**Comment by thockin** [comment] 2015-12-29 03:52
Obviously I disagree.  You're linking two things that are not related - the
go version I happen to have and the behavior I want from godep.

Using the same env var at all is a bit clumsy, you should really just have
a flag and let the user say what they want, rather than trying to infer
wrongly.

The env var manipulates behavior of Go for versions of Go that know about
the variable.  It should likewise manipulate the behavior of godep for
versions of godep that know about the variable.  No looking at other tools.

**Closed** 2016-05-12 21:35 UTC
