### ISSUE TITLE
save and update strips out long lines of code

### ISSUE THREAD

**Issue by 9uuso** [tools/godep#160] opened 2014-12-16 19:19 UTC
Hello,

I've faced really confusing error with packages which have really long source code lines. I'm not sure is this really an error in `godep` or is it a bug in Go standard library, but I thought it might be a good idea to start here.

Basically, I was trying to import package [`unicode`](https://github.com/rainycape/unidecode), which built fine with my application on my development machine. However, after dumping the dependency and trying to run tests for it on my CI service, I got error saying that the variable [`tableData`](https://github.com/rainycape/unidecode/blob/master/table.go#L5) was undefined.

I initially though this was a problem with the `unidecode` package's git import path, so I vendored the package, but it did not fix the problem.

Eventually I tried importing the variable in my [vendored package](https://github.com/9uuso/unidecode/blob/master/unidecode.go#L29) by splitting the line into five variables.

When I tried to include the updated package in my project, I noticed from that SourceTree indicated line removals after running `go get -u github.com/9uuso/unidecode` and `godep update github.com/9uuso/unidecode`. These line removals were made after [line 28](https://github.com/9uuso/unidecode/blob/master/unidecode.go#L28). Line 28 was now the last line of the file.

![screenshot 2014-12-16 21 17 10](https://cloud.githubusercontent.com/assets/1684211/5460132/f9020f58-8568-11e4-9c64-7a0898b98dd6.png)

I now checked my application's git history and saw that the line where the `tableData` should have been, [was missing](https://github.com/9uuso/vertigo/blob/f0730970e994ee45cc90ac2746df43bb9f576edf/Godeps/_workspace/src/gopkgs.com/unidecode.v1/table.go), even though when comparing with the original package, [it was there](https://github.com/rainycape/unidecode/blob/master/table.go#L5). The git commit hash in the [Godeps.json](https://github.com/9uuso/vertigo/blob/f0730970e994ee45cc90ac2746df43bb9f576edf/Godeps/Godeps.json#L160) and in the latest [unidecode commit](https://github.com/rainycape/unidecode/commit/4deae2c05236b41cc39f8144ac87a837ba974d40) matched.

The bug can be worked around by manually adding the line to the Godeps folder.

Any input on this?

**Comment by felixge** [comment] 2015-01-13 20:31
Just ran into this as well. The problem is here: https://github.com/tools/godep/blob/0baa7ea464025b2cb8e84b13c5ac4da99237a1bf/save.go#L358 . `bufio.Scanner` cannot handle lines > `bufio.MaxScanTokenSize` (64 KB). A common case where this comes up is when importing go files that embed static files (e.g. when using https://github.com/rakyll/statik).

I'll try to submit a patch if I get a chance to work on this.

**Comment by freeformz** [comment] 2015-06-17 23:06
This should now be fixed by #231.

**Closed by freeformz** 2015-06-17 23:06 UTC
