### ISSUE TITLE
godep not functioning with go 1.4 (linux/386)

### ISSUE THREAD

**Issue by gshields** [tools/godep#168] opened 2014-12-31 21:47 UTC
ghs@ghs-kp:~/go-programs$ godep path
godep: No Godeps found (or in any parent directory)
ghs@ghs-kp:~/go-programs$ go env
GOARCH="386"
GOBIN=""
GOCHAR="8"
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ghs/go-programs"
GORACE=""
GOROOT="/home/ghs/go"
GOTOOLDIR="/home/ghs/go/pkg/tool/linux_386"
CC="gcc"
GOGCCFLAGS="-fPIC -m32 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by cybertk** [comment] 2015-05-10 17:49
+1

**Comment by freeformz** [comment] 2015-10-08 22:16
I'm going to close this as I can't reproduce it. If this is still an issue please re-open with steps to reproduce.

**Closed by freeformz** 2015-10-08 22:16 UTC
