### ISSUE TITLE
v36 unable to `godep restore` but v34 works(ish)

### ISSUE THREAD

**Issue by eparis** [tools/godep#359] opened 2015-12-14 18:22 UTC
```
go get -u k8s.io/kubernetes
go get -u github.com/tools/godep

cd $GOPATH/src/k8s.io/kubernetes
$GOPATH/bin/godep restore
```
Fails with:
```
godep: error restoring dep (github.com/Sirupsen/logrus): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.aSHREx/src/github.com/Sirupsen/logrus
godep: error restoring dep (github.com/boltdb/bolt): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.aSHREx/src/github.com/boltdb/bolt
godep: error restoring dep (github.com/docker/docker/pkg/jsonmessage): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.aSHREx/src/github.com/Sirupsen/logrus
godep: error restoring dep (github.com/docker/docker/pkg/term): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.aSHREx/src/github.com/Sirupsen/logrus
godep: error restoring dep (github.com/docker/libcontainer): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.aSHREx/src/github.com/Sirupsen/logrus
godep: error restoring dep (github.com/google/cadvisor/api): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.aSHREx/src/github.com/Sirupsen/logrus
godep: error restoring dep (github.com/google/cadvisor/http): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.aSHREx/src/github.com/Sirupsen/logrus
godep: error restoring dep (github.com/google/cadvisor/manager): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.aSHREx/src/github.com/Sirupsen/logrus
godep: error restoring dep (github.com/google/cadvisor/pages): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.aSHREx/src/github.com/Sirupsen/logrus
godep: error restoring dep (github.com/google/cadvisor/validate): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath.aSHREx/src/github.com/Sirupsen/logrus
```

```
cd $GOPATH/src/github.com/tools/godep
git checkout v34
go install github.com/tools/godep

cd $GOPATH/src/k8s.io/kubernetes
$GOPATH/bin/godep restore
```
Returns without error

**Comment by eparis** [comment] 2015-12-14 18:23
(or at least I should say the v34 returns wihout an error)

```
rm -rf Godeps
$GOPATH/bin/godep save ./...
```

Appears to hang forever....

**Comment by eparis** [comment] 2015-12-14 18:27
v33 dies with
```
godep: error restoring dep (github.com/google/btree): found packages btree (btree.go) and main (btree_mem.go) in /tmp/gopath.aSHREx/src/github.com/google/btree
godep: error restoring dep (golang.org/x/tools/imports): found packages imports (fix.go) and main (mkindex.go) in /tmp/gopath.aSHREx/src/golang.org/x/tools/imports
```

**Comment by freeformz** [comment] 2015-12-14 18:28
@eparis GO15VENDOREXPERIMENT=1 ?

**Comment by eparis** [comment] 2015-12-14 18:28
no

**Comment by eparis** [comment] 2015-12-14 18:38
v32 appears to be the last version that the k8s.io/kubernetes (github.com/kubernetes/kubernetes) project is able to do:
```
godep restore
rm -rf Godeps/
godep save
```

**Comment by freeformz** [comment] 2015-12-14 19:04
This is probably because these newer versions are more inclusive wrt what they'll vendor and the same rules are being applied to restore, so it's not finding a package it thinks should be vendored. :-( 

I wonder if doing a `go get golang.org/x/sys/unix` will take care of it and/or change the errors?

**Comment by freeformz** [comment] 2015-12-14 19:06
For some more clarity we only ignore files tagged with `ignore` and `appengine` build tags. Before `go list` would also filter out any non local platform files. This caused issues in that a lot of development happens on OSX, but deployments happen on Linux. So if your deps required an extra package on Linux, they wouldn't be saved and then your build would likely fail (depending how how you setup your environment TBH and lots of people mistook how godeps works because of this).

**Comment by freeformz** [comment] 2015-12-14 19:07
I'm going to poke at this early this afternoon (Pacific/US) and see if I can provide better guidence / work around / suggestions / patch / etc.

**Comment by eparis** [comment] 2015-12-14 19:10
`go get golang.org/x/sys/unix` makes that error go away
But I got another one which I could make go away. I'll get the details.

**Comment by eparis** [comment] 2015-12-14 19:27
```
godep: error restoring dep (github.com/google/cadvisor/validate): Unable to find dependent package github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp in context of /tmp/gopath.9G0wU0/src/github.com/fsouza/go-dockerclient
```
`go get github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp` does not however let me proceed.

**Comment by freeformz** [comment] 2015-12-14 19:32
This is what I get currently on master with godep v36:

```console
$ mkdir ~/go2
$ export GOPATH=~/go2
$ go get -u k8s.io/kubernetes
package k8s.io/kubernetes: no buildable Go source files in /Users/emuller/go2/src/k8s.io/kubernetes
$ cd ~/go2/src/k8s.io/kubernetes
$ godep restore
godep: error downloading dep (github.com/google/cadvisor/api): exit status 1
godep: error downloading dep (github.com/google/cadvisor/http): exit status 1
godep: error downloading dep (github.com/google/cadvisor/manager): exit status 1
godep: error downloading dep (github.com/google/cadvisor/pages): exit status 1
godep: error downloading dep (github.com/google/cadvisor/validate): exit status 1
godep: error downloading dep (golang.org/x/exp/inotify): exit status 1
```

These restore issues may be related to something else I need to look into. Digging.

**Comment by eparis** [comment] 2015-12-14 19:33
transient github error?

**Comment by freeformz** [comment] 2015-12-14 19:37
Not sure. There is also an issue where restore will fail (currently) if the dep package is no longer available in master (that's the issue I was referring to, not sure the number). I'd like to fix that issue this week, but may be unrelated.

**Comment by freeformz** [comment] 2015-12-14 19:39
```console
$ go get -d github.com/google/cadvisor/api
container/raw/handler.go:38:2: no buildable Go source files in /Users/emuller/go2/src/golang.org/x/exp/inotify
```

cadvisor is having issues on master. This is basically the same bug as the one I mentioned.

**Comment by freeformz** [comment] 2015-12-14 19:41
FWIW: the cadvisor issue has nothing to do with godeps per se. Master isn't even buildable for me.

**Comment by freeformz** [comment] 2015-12-14 19:42
@eparis BTW: I wasn't able to reproduce the initial issue (`Unable to find dependent package golang.org/x/sys/unix`). What OS was that restore run on ?

**Comment by freeformz** [comment] 2015-12-14 19:43
I suspect it was linux. If so you probably want to re-save using v35 to pick up new deps.

**Comment by eparis** [comment] 2015-12-14 19:44
I did it on Fedora 23 (linux), godep built with 1.5.1...
@yifan-gu hit the same problem.  Not sure his OS

**Comment by eparis** [comment] 2015-12-14 19:49
v36
```
godep: error restoring dep (github.com/boltdb/bolt): Unable to find dependent package golang.org/x/sys/unix in context of /storage/gopath/src/github.com/boltdb/bolt
```

**Comment by yifan-gu** [comment] 2015-12-14 19:51
My is ubuntu 15.04, go version go1.4.2 linux/amd64

**Comment by eparis** [comment] 2015-12-14 20:03
`godep restore` on linux into an empty GOPATH, v36, fails with unable to find dependent package for

```
github.com/Azure/go-ansiterm/winterm
github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp
```

if I `go get` those by hand, `godep restore` will run fine. But `godep save` does not pull those into Godeps, so the next `godep restore` into an empty GOPATH fails...

**Comment by freeformz** [comment] 2015-12-14 20:09
That's possible. I'll make a linux VM /  AWS instance after lunch and duplicate / etc.

**Comment by freeformz** [comment] 2015-12-15 00:10
Duplicated in a linux docker container:

```console
$ godep restore
godep: error restoring dep (github.com/Sirupsen/logrus): Unable to find dependent package golang.org/x/sys/unix in context of /app/user/src/github.com/Sirupsen/logrus
godep: error restoring dep (github.com/boltdb/bolt): Unable to find dependent package golang.org/x/sys/unix in context of /app/user/src/github.com/boltdb/bolt
godep: error restoring dep (github.com/docker/docker/pkg/jsonmessage): Unable to find dependent package github.com/Azure/go-ansiterm/winterm in context of /app/user/src/github.com/docker/docker/pkg/term
godep: error restoring dep (github.com/docker/docker/pkg/term): Unable to find dependent package github.com/Azure/go-ansiterm/winterm in context of /app/user/src/github.com/docker/docker/pkg/term
godep: error restoring dep (github.com/docker/libcontainer): Unable to find dependent package golang.org/x/sys/unix in context of /app/user/src/github.com/Sirupsen/logrus

godep: error restoring dep (github.com/google/cadvisor/api): Unable to find dependent package github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp in context of /app/user/src/github.com/fsouza/go-dockerclient
godep: error restoring dep (github.com/google/cadvisor/http): Unable to find dependent package github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp in context of /app/user/src/github.com/fsouza/go-dockerclient
godep: error restoring dep (github.com/google/cadvisor/manager): Unable to find dependent package github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp in context of /app/user/src/github.com/fsouza/go-dockerclient
godep: error restoring dep (github.com/google/cadvisor/pages): Unable to find dependent package github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp in context of /app/user/src/github.com/fsouza/go-dockerclient
godep: error restoring dep (github.com/google/cadvisor/validate): Unable to find dependent package github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp in context of /app/user/src/github.com/fsouza/go-dockerclient
```


Some of these are confirmed platform specific transitive dependencies that were missed by older versions of godep.

In the case of logrus & bolt they both import `golang.org/x/sys/unix` on solaris.
`docker/docker/pkg/term` has a windows specific transitive import on `github.com/Azure/go-ansiterm"`

The `github.com/fsouza/go-dockerclient/external/github.com/hashicorp/go-cleanhttp` errors are something else, possibly related to an ordering issue in the restore code.

I'm looking into this and other stuff.

**Comment by eparis** [comment] 2015-12-15 00:35
Awesome, glad you're digging in. I'll be excited to know why `godep save ./...` handles the `solaris:golang.org/x/sys/unix` but not the `windows:github.com/Azure/go-ansiterm`

**Comment by freeformz** [comment] 2015-12-15 04:49
@eparis See #362 along with kubernetes/kubernetes/18695

**Comment by thanodnl** [comment] 2015-12-15 14:49
I was running into the same issue today :(, but I have some information for you!

Running a `git bisect` on godep points me to this commit as the cause of the failure: https://github.com/tools/godep/commit/6bb9038f1fdeb750441c6341c8fa785034ba9e0c

With this version of logrus:
```json
{
    "ImportPath": "github.com/Sirupsen/logrus",
    "Comment": "v0.8.6-25-g82c8de1",
    "Rev": "82c8de1af23b25ba5a468d801f29077f4f483bce"
}
```

and the following error output of `godep restore`:
```
godep: error restoring dep (github.com/Sirupsen/logrus): Unable to find dependent package golang.org/x/sys/unix in context of /tmp/gopath/src/github.com/Sirupsen/logrus
```

I indeed do not have specified `golang.org/x/sys/unix` as a Godep since the version of logrus I'm using does not yet depend on this package. As you will see [here](https://github.com/Sirupsen/logrus/tree/82c8de1af23b25ba5a468d801f29077f4f483bce) the [terminal_solaris.go](https://github.com/Sirupsen/logrus/blob/master/terminal_solaris.go) file that depends on `golang.org/x/sys/unix` is not yet in the version I'm using.

It looks like `godep restore` tries to restore a different -possibly later- version of logrus than I want to be restored.

Hope this helps you in finding the issue more quickly.

**Comment by eparis** [comment] 2015-12-15 14:54
@thanodnl #362 fixes the problem(s) for me. It does start pulling in `golang.org/x/sys/unix` which I didn't check if that was correct/needed...

**Comment by thanodnl** [comment] 2015-12-15 14:58
@eparis I do not see `golang.org/x/sys/unix` showing up in my path and neither in my Godeps.json after I do a `godep save ./...`. Could it be that you bumped the version of `logrus` in the process, hence explaining why it now adds `x/sys/unix` to your deps?

**Comment by freeformz** [comment] 2015-12-15 17:45
@thanodnl Previous to #362 godep loaded the packages before checking out the specified versions. This caused problems, especially with other recent changes (but they were present before anyway, just less pronounced).

@eparis You guys need `golang.org/x/sys/unix` because of bolt:
```console
$ godep restore -v
...
godep: Checking dependency: github.com/boltdb/bolt
godep: Dep (github.com/boltdb/bolt) restored, but was unable to load it with error:
	Unable to find dependent package golang.org/x/sys/unix in context of /Users/emuller/go2/src/github.com/boltdb/bolt
godep: 	This may be because the dependencies were saved with an older version of godep (< v33).
godep: 	Try `go get golang.org/x/sys/unix`. Then `godep save` to update deps.
...
```

**Comment by ironcladlou** [comment] 2015-12-15 20:28
>Not sure. There is also an issue where restore will fail (currently) if the dep package is no longer available in master (that's the issue I was referring to, not sure the number). I'd like to fix that issue this week, but may be unrelated.

I believe you're referring to #186.

**Comment by freeformz** [comment] 2015-12-15 22:38
@ironcladlou yes. Thanks. Marked as resolved.

**Closed** 2015-12-15 22:41 UTC
