### ISSUE TITLE
godep save broken since v32

### ISSUE THREAD

**Issue by snikch** [tools/godep#361] opened 2015-12-15 04:03 UTC
I came here to note that I too have found an issue with versions of godep after `v32`. I'm not sure if this is the same issue as #359, so I'm opening a separate issue.

When I run `godep save ./...` I only get the first level of dependencies vendored. If my code includes package `a` and package `a` includes package `b`, then I will only see package `a` in my `vendor` folder. If I run `godep save ./...` again, then I get package `b`, but not any packages that package `b` imports.

I can repeat this ad infinium, until a tree of every possible import is built up - however this will include packages which aren't actually directly compiled into my code, as it imports all dependencies of every package in the same source control repo as the target packages.

Note: I'm using `GO15VENDOREXPERIMENT=1` but I'm not sure that matters.

Here's an example of a clean godep save at commit `cf33bd7`, the last commit where I get a "correct" vendor dir.

```
➜  polecat git:(event-ingestion) ✗ rm -rf vendor && rm -rf Godeps && godep save ./... && ls -l vendor/github.com
total 0
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 ConradIrwin
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 Shopify
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 Sirupsen
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 bugsnag
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 dgrijalva
drwxr-xr-x  4 mal  staff  136 Dec 15 16:54 eapache
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 elgris
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 go-sql-driver
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 golang
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 gorilla
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 jmoiron
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 julienschmidt
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 klauspost
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 kylelemons
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 lib
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 mitchellh
drwxr-xr-x  4 mal  staff  136 Dec 15 16:54 onsi
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 samuel
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 snikch
drwxr-xr-x  4 mal  staff  136 Dec 15 16:54 vend
drwxr-xr-x  4 mal  staff  136 Dec 15 16:54 wvanbergen
drwxr-xr-x  5 mal  staff  170 Dec 15 16:54 xeipuuv
drwxr-xr-x  3 mal  staff  102 Dec 15 16:54 ziutek
```

And from every commit after that up until commit `674153d` I get an error;

```
➜  polecat git:(event-ingestion) ✗ rm -rf vendor && rm -rf Godeps && godep save ./... && ls -l vendor/github.com
godep: no buildable Go source files in /Users/mal/Code/src/github.com/vend/polecat
```

And then from `b29279c` up to master, I get the following, partial vendor dir.

```
➜  polecat git:(event-ingestion) ✗ rm -rf vendor && rm -rf Godeps && godep save ./... && ls -l vendor/github.com
total 0
drwxr-xr-x  3 mal  staff  102 Dec 15 16:51 Shopify
drwxr-xr-x  3 mal  staff  102 Dec 15 16:51 Sirupsen
drwxr-xr-x  3 mal  staff  102 Dec 15 16:51 dgrijalva
drwxr-xr-x  3 mal  staff  102 Dec 15 16:51 elgris
drwxr-xr-x  3 mal  staff  102 Dec 15 16:51 gorilla
drwxr-xr-x  3 mal  staff  102 Dec 15 16:51 jmoiron
drwxr-xr-x  3 mal  staff  102 Dec 15 16:51 julienschmidt
drwxr-xr-x  4 mal  staff  136 Dec 15 16:51 onsi
drwxr-xr-x  3 mal  staff  102 Dec 15 16:51 snikch
drwxr-xr-x  4 mal  staff  136 Dec 15 16:51 vend
drwxr-xr-x  4 mal  staff  136 Dec 15 16:51 wvanbergen
drwxr-xr-x  3 mal  staff  102 Dec 15 16:51 xeipuuv
```

**Comment by freeformz** [comment] 2015-12-15 04:22
If you are using GO15VENDOREXPERIMENT (and it looks like you are) and running v35 then update to v36 (https://github.com/tools/godep/issues/358)  and let me know if there is still an issue.

I'm going to start committing GO15VENDOREXPERIMENT related tests tomorrow (hopefully) and if not I'd like to get a reproducable test case for this.

**Comment by snikch** [comment] 2015-12-15 04:24
Still an issue, using master.

```
➜  polecat git:(event-ingestion) ✗ godep version
godep v36 (darwin/amd64/go1.5.2)
➜  polecat git:(event-ingestion) ✗ rm -rf vendor && rm -rf Godeps && godep save ./... && ls -l vendor/github.com
total 0
drwxr-xr-x  3 mal  staff  102 Dec 15 17:24 Shopify
drwxr-xr-x  3 mal  staff  102 Dec 15 17:24 Sirupsen
drwxr-xr-x  3 mal  staff  102 Dec 15 17:24 dgrijalva
drwxr-xr-x  3 mal  staff  102 Dec 15 17:24 elgris
drwxr-xr-x  3 mal  staff  102 Dec 15 17:24 gorilla
drwxr-xr-x  3 mal  staff  102 Dec 15 17:24 jmoiron
drwxr-xr-x  3 mal  staff  102 Dec 15 17:24 julienschmidt
drwxr-xr-x  4 mal  staff  136 Dec 15 17:24 onsi
drwxr-xr-x  3 mal  staff  102 Dec 15 17:24 snikch
drwxr-xr-x  4 mal  staff  136 Dec 15 17:24 vend
drwxr-xr-x  4 mal  staff  136 Dec 15 17:24 wvanbergen
drwxr-xr-x  3 mal  staff  102 Dec 15 17:24 xeipuuv
```

**Comment by freeformz** [comment] 2015-12-15 04:51
I'll see if I can make a small repro tomorrow (although I probably won't get to it until the afternoon).

**Comment by snikch** [comment] 2015-12-15 06:41
All good :+1:, I'm happy enough in the meantime with the older version! Thanks.

**Comment by freeformz** [comment] 2015-12-22 05:55
Closing in favor of #358

**Closed by freeformz** 2015-12-22 05:55 UTC
