### ISSUE TITLE
godep save doesn't make _Workspace and vendor folder.

### ISSUE THREAD

**Issue by ttomato** [tools/godep#527] opened 2016-12-19 09:49 UTC
### Expected behavior
Generate vendor folder.

### Actual behavior
No vendor folder, and no _workspace folder in Godeps. Just Godeps.json and Readme. 

### Steps to reproduce behavior
godep save ./...

### `godep version` output
godep v75 (darwin/amd64/go1.7.3)

### `go version` output
go version go1.7.3 darwin/amd64

### Contents of Godeps.json file
{
	"ImportPath": ".",
	"GoVersion": "go1.7",
	"GodepVersion": "v75",
	"Packages": [
		"./..."
	],
	"Deps": []
}

**Comment by 1ambda** [comment] 2016-12-23 04:39
It happened when `Godep` doens't changed at all. To reproduce this issue,

1. Remove `vendor` dir
2. Run `godep save ./...`
3. Execute `ls vendor`

```
$ godep version
godep v75 (darwin/amd64/go1.7.3)
$ go version
go version go1.7.3 darwin/amd64
```

**Comment by freeformz** [comment] 2018-02-15 21:54
I am closing this issue because the repo is going to be archived.

**Closed by freeformz** 2018-02-15 21:54 UTC
Labels: ClosedToArchive
